module.exports = {
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN:'INVALID_TOKEN',
  USER_INACTIVE:'USER_INACTIVE',
  USER_DELETED:'USER_DELETED',
  USER_NOT_FOUND:'USER_NOT_FOUND'
};
