module.exports={
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_NAME_EXISTS: 'TEAM_NAME_EXISTS',
  TEAM_INACTIVE: 'TEAM_INACTIVE',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
  INVALID_TEAM_NAME: 'INVALID_TEAM_NAME',
  INVALID_STATUS: 'INVALID_STATUS',
  TEAM_ALREADY_EXISTS:'TEAM_ALREADY_EXISTS'
}