module.exports={
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_NAME_EXISTS: 'TEAM_NAME_EXISTS',
  TEAM_INACTIVE: 'TEAM_INACTIVE',
  UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
  INVALID_TEAM_NAME: 'INVALID_TEAM_NAME',
  INVALID_STATUS: 'INVALID_STATUS',
  TEAM_ALREADY_EXISTS:'TEAM_ALREADY_EXISTS',
  USER_NOT_FOUND:'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE', 
  INVALID_USER:'INVALID_USER', 
  DIFFERENT_ORGANIZATION: 'DIFFERENT_ORGANIZATION',
  MEMBER_ALREADY_ACTIVE: 'MEMBER_ALREADY_ACTIVE',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  INVALID_MANAGER:'INVALID_MANAGER',
  CANNOT_REMOVE_MEMBER:'CANNOT_REMOVE_MEMBER'
}